[libraries]
minecraft-plugin-worldguard = "com.sk89q.worldguard:worldguard-bukkit:7.0.7"
minecraft-plugin-geary-papermc = "com.mineinabyss:geary-papermc:0.24-SNAPSHOT"
minecraft-plugin-blocky = "com.mineinabyss:blocky:0.6-SNAPSHOT"
